- name: Install terraform
  hosts: localhost
  become: true
  vars:
    terraform_arch: "amd64"

  tasks:
    - name: Install terraform  prerequisites for Ubuntu/Debian 
      apt:
        name:
          - gnupg
          - software-properties-common
          - wget
          - unzip
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add HashiCorp GPG key (Ubuntu/Debian)
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add HashiCorp repository (Ubuntu/Debian)
      apt_repository:
        repo: "deb [arch={{ terraform_arch }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Terraform from repository (Ubuntu/Debian)
      apt:
        name: terraform
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"