services:

  # =========================
  #    GITLAB CE (OMNIBUS)
  # =========================
  gitlab:
    image: gitlab/gitlab-ce:17.6.0-ce.0 # mage officielle de GitLab CE  version fixée contient GitLab + PostgreSQL + Redis (Omnibus)
    container_name: gitlab #nom du container facile à identifier dans docker ps
    hostname: gitlab.local #nom interne de la machine (dans Docker)  utilisé dans réseau interne
    restart: always #redémarrage automatique

    environment:
      GITLAB_OMNIBUS_CONFIG: | #ce que les utilisateurs ouvrent dans le navigateur  c'est ip de vm2
        external_url 'http://100.71.2.191:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 6022
        gitlab_rails['time_zone'] = 'Europe/Paris'

    ports:
      - "8080:80" # HTTP
      - "8443:443" # HTTPS (option)
      - "6022:22" # SSH Git

    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    networks:
      - gitlab_net

  # =========================
  #       GITLAB RUNNER
  # =========================
  gitlab-runner:
    image: gitlab/gitlab-runner:v17.6.0
    container_name: gitlab-runner
    restart: always

    depends_on:
      - gitlab

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner

    networks:
      - gitlab_net

# =========================
#         VOLUMES
# =========================
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

    # =========================
    #          NETWORK
    # =========================
networks:
  gitlab_net:
