version: '3.8'

services:

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always

    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube_db
      SONAR_JDBC_USERNAME: chaimae
      SONAR_JDBC_PASSWORD: chaimae1702
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      # Keycloak SAML SSO
      SONAR_AUTH_SAML_ENABLED: "true"
      SONAR_AUTH_SAML_APPLICATIONID: "sonarqube"
      SONAR_AUTH_SAML_PROVIDERNAME: "Keycloak"
      SONAR_AUTH_SAML_PROVIDERID: "http://100.124.103.20:8081/realms/projet-portfolio"
      SONAR_AUTH_SAML_LOGINURL: "http://100.124.103.20:8081/realms/projet-portfolio/protocol/saml"
      SONAR_AUTH_SAML_USERNAMEATTRIBUTE: "preferred_username"
      SONAR_AUTH_SAML_USEREMAILATTRIBUTE: "email"
      SONAR_AUTH_SAML_GROUPSATTRIBUTE: "groups"
      SONAR_AUTH_SAML_CERTIFICATE: "MIICrzCCAZcCBgGeMrRM7TANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBwcm9qZXQtcG9ydGZvbGlvMB4XDTI2MDUxNjIxMzAzN1oXDTM2MDUxNjIxMzIxN1owGzEZMBcGA1UEAwwQcHJvamV0LXBvcnRmb2xpbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANIGQvlNDTTiAf1WDeAkPl1ar5ipdQTK0JTpGsLffTxF2upywlD8MsK/zCq/IcAzipdRlwP99+rHdGfPH6o8oxg2ii+4bGBlahzOmheKr438B882eTjzEadh6vml/wtqzvrcDejb6m41Zw6hHHwJnouhrMbS9+dd19gbGimmQ/EP43lbVLH5pFUN7kR2KVgIbQCNkZSjqdA/otUFlW0mUDOsg0FJ03mDDYEsJ66pczg9pzp7v6uwxOSVAFQrnSmRPYOmURfGeBYlI1802lvVAHilCNBpa0hDObdW75c7qTXXV+YK0LKokvDcoKm9Vhb1ADAO2sELRWVtXbNEkXGjAh8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAmwF8Yo5ccKY3F0DahEkK1YHL2IvE8OtoVi5/ucLXO1C6oJFqMUx8Oi095KUSVgww4FPs0Qh8V+ptD7VNVr9UJ3d8SCtQkccV2TMHEhCBK6KG69XJ0XjLnAdyXKPGKAr4/Est1KQqy9bydh7qAklCP/nK5Ootn+83Gk+Aa7lElQa8kwSf/kwVsBg3nTsrs2u6z+JzmAKXtVL9JQspzIvnuqePFs5o3yicJ0XoWxhu/+/sFh1NvYIUOqI3oPO6dPXiSFKra26Le0XGaRXJYloUDJgByli1ugFf2m2VrHgHWJxX0qqAV5A84id2t7ieuQFZsoldbSi15OsoHqaeUdPTaw=="

    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

    networks:
      - app_network

volumes:
  sonarqube_data:
  sonarqube_logs:

networks:
  app_network:
    external: true

