[master]
muestra-master ansible_host=100.94.135.53 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]

[workers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@100.94.135.53'

[master:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
