[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[master]
master.muestra.qzz.io

[master:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='cloudflared access ssh --hostname %h --id 09972a53988f7b8467a1624b9c94f642.access --secret c2efa5bc25d6af516a057ba2a48b1d5f7fbbf095c083447cb16268e4c028295e'

[workers]
muestra-node-1 ansible_host=10.0.1.97

[workers:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyJump='ubuntu@master.muestra.qzz.io'
