- name: Stop GitLab Stack Securely
  hosts: devsecops
  become: true
  vars:
    app_dir: /opt/gitlab-stack

  tasks:

    - name: Check stack exists
      stat:
        path: "{{ app_dir }}/docker-compose.yml"
      register: stack_file

    - name: Stop stack safely
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: absent
      when: stack_file.stat.exists
