- name: Deploy GitLab Stack Securely
  hosts: devsecops
  become: true
  vars:
    - app_dir: "{{ ansible_user_dir }}/app"

  vars:
    app_dir: /opt/gitlab-stack

  tasks:

    #  Vérifier Docker
    - name: Check Docker installed
      command: docker --version
      register: docker_check
      failed_when: docker_check.rc != 0
      changed_when: false

    #  Créer dossier sécurisé
    - name: Create secure directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0750'

    #  Copier docker  compose
    - name: Copy docker compose
      copy:
        src: docker-compose-gitlab.yml
        dest: /home/kaoutarbendidi/app/docker-compose.yml

    - name: Run docker compose
      command: docker compose up -d
      args:
        chdir: /home/kaoutarbendidi/app
